### ISSUE TITLE
Plugin isn't accounting for multiple En languages

### ISSUE THREAD

**Issue by jackcarrington** [ControlZetaDigital/polylang-tcopro#2] opened 2023-11-16 13:17 UTC
I’ve noticed that the plugin isn’t accounting for multiple English language pages where the 'lang' has to be different to create a variation.

hreflang=“en” /> - works
hreflang=“en-GB” />  - not listed
hreflang=“en-AU” />  - not listed
hreflang=“en-ZA” />  - not listed

Thanks

**Comment by ControlZetaDigital** [comment] 2023-11-16 17:23
Hi Jack, could you please attach a screenshot of the plugin's admin page and Polylang's languages page of where you found the issue?

Thanks

**Comment by jackcarrington** [comment] 2023-11-16 20:32
It's fine! 

I've been using Polylang in a different way from the norm - my English lang alternatives don't have translated posts. I use them like categories and show en posts on an en-au page. 

but once i added a test post to the lang - it showed the language in your plugin 😅 

So if anyone is using it like a plumb as I am, they need at least one translated post for the flag to appear in the plugin.

**Comment by ControlZetaDigital** [comment] 2023-11-16 22:00
That's great, I'm glad to know that you were able to solve it in the end and wasn't caused by a bug. I proceed to close the issue then. Greetings!

**Closed as completed** 2023-11-16 22:01 UTC
